### ISSUE TITLE
after update stop working

### ISSUE THREAD

**Issue by nexik** [coduo/phpspec-prepare-extension#6]
After upgrading phpspec to current version (2.4.0) I got this errors

```
warning: call_user_func_array() expects parameter 1 to be a valid callback, 
first array member is not a valid class name or object in
/project/vendor/phpspec/phpspec/src/PhpSpec/ObjectBehavior.php line 137
```

when I use before annotation

**Comment by norberttech** [comment]
Thanks for reporting that, could you provide some simple example of spec that can be used to reproduce that bug?

**Comment by nexik** [comment]
Now I am out of office. I will post example tomorrow.

**Comment by nexik** [comment]
It seems I had some problems with my PHP installation with opcache. After reinstalling it, the problem no longer exists.
